### PR TITLE
Adds more methods to the WindowInfo class

### PR DESCRIPTION
**Pull request by kdschlosser**
see class docstring

### CODE REVIEW

**Comment by kdschlosser** [comment]
On this one I didn't actually test this thing. But it gives some additional ideas. I don't have a working EG at the moment. I have cut them all up LOL. So I am going to have to compile it again... But if you want to give it a go and see what does and does not work that would help greatly.

**Comment by kdschlosser** [comment]
I just wanted to let you know I have gone through the additions and fixed most of the issues. The Animate is not working properly I will dig into that more later.

**Comment by Boolean263** [comment]
You don't need to close this one. I only haven't merged it yet because you said you weren't done with it. Have you worked out the issues with Animate?

I'm sorry I reacted how I did. It's just insulting to be given a line-by-line explanation of your code when you already write it to be clear and understandable.

**Comment by Boolean263** [comment]
I decided to bring in these function changes, since I was in mucking around with other stuff anyway. They've moved to WindowInfo.py, but they're all there (some with some minor tweaks).

I decided not to add the 'help' attribute, since PyCharm and other good IDEs should show that info from the functions' docstrings.

Thanks again for your hugely useful contribution!

**Comment by kdschlosser** [comment]
the help was not there for the people that use an IDE. it was there for the people that use EG. also the docstrings have to be formatted a specific way the remove of the extra white space and any tabs or indents and markers cannot be done otherwise the the use of an external package to convert the docstrings into html or some other type of formatted output will not function. and I do not believe the information that is spit out by use of help() in pycrust would come out correct either without the markers empty lines and indenting. I would have to test it with pycrust to be sure on that one. 

things like Attributes: and then indenting and listing all of the class attributes needs to be there as well.

the help i added so a user could simply plop into a python command print eg.event.payload.help and tie an event generated by the plugin to it so it would print out the help docs. now we could do a __str__(self) as a method so if they did a print eg.event.payload to see what the payload actually was it would spit out the help. 

I also changed the repr value to what the payload actually is. it is a dynamically created WindowInfo class object. yours looks as tho title={} is an empty dict and window_class={} is an empty dict as well and this could be misleading.

**Comment by kdschlosser** [comment]
Oh and one other thing is the use of caching of the title could cause issues if someone is looking for a blank title. in order to do something. because the title can be changed to that for a specific reason what it would be i do not know. but returning a title that the window does not have would give incorrect information to the user.

Now I do not know if only having a closed window is the only way for the title to be empty. if the window gets closed it would be moot if it did anyways because there should be no WindowInfo class attached to a closed event because the window no longer exists and none of the methods in it can function properly.

**Comment by Boolean263** [comment]
> I also changed the repr value to what the payload actually is. it is a dynamically created WindowInfo class object. yours looks as tho title={} is an empty dict and window_class={} is an empty dict as well and this could be misleading.

The `{}` parts don't appear in the final result of the repr() call. They're used by the [str.format()](https://docs.python.org/2/library/stdtypes.html#str.format) as markers for where the replacement text should go in the string. In this case, I've passed `repr(self.title)` and `repr(self.window_class)` as the two arguments. So when you use `repr(eg.event.payload)` you see something like this: `<title=u'Untitled - Notepad', window_class=u'Notepad',...>` If you turn on logging for all events in EventGhost, you'll also see it there. It says in the Python documentation (that I linked above) that "This method of string formatting is the new standard in Python 3, and _should be preferred ... in new code._" (emphasis mine) It's supported in Python 2 as well, as you'll see if you try it out.

> I do not believe the information that is spit out by use of help() in pycrust would come out correct either without the markers empty lines and indenting. I would have to test it with pycrust to be sure on that one.

You really should test it out. It looks fine to me when I test it in PyCrust. Here's what I get with a quick test (which also demonstrates what I was saying about `repr()` above):

    >>> sys.path.append('E:\\Program Files (x86)\\EventGhost\\plugins')
    >>> from TaskMonitorPlus.WindowInfo import WindowInfo
    >>> w = WindowInfo(eg.messageReceiver.hwnd)
    >>> w
    <title=u'EventGhost Message Receiver', window_class=u'EventGhost Message ReceiverMessageReceiver',...>
    >>> help(w.Focus)
    Help on method Focus in module TaskMonitorPlus.WindowInfo:
    
    Focus(self) method of TaskMonitorPlus.WindowInfo.WindowInfo instance
        Makes the window in focus.
        :return: None
        :rtype: None
    
    >>> 

If I simply do `help(w)` after that, I get a full listing of all the docstrings in the class. I see no need to reinvent Python's built-in help system when it seems to do the job.

> Oh and one other thing is the use of caching of the title could cause issues if someone is looking for a blank title. in order to do something. because the title can be changed to that for a specific reason what it would be i do not know. but returning a title that the window does not have would give incorrect information to the user.

While that is true, I cached the title because, without the cache, `ClosedWindow` events would have a payload with no title and no window class, because `GetWindowText()` and `GetClassName()` respectively return the empty string when called with a `hwnd` representing a window that is no longer in existence. So for example, you couldn't tell the difference between closing the PyCrust window and closing the EventGhost main window, because both would generate `TaskMonitorPlus.ClosedWindow.EventGhost` events, and the `title` attribute of the payload would otherwise be blank. This way, the `title` attribute still says 'PyCrust' (I just tested it to be sure), so I can tell which window was closed.

If I use `IsAlive()` to determine whether to return the cached result, that would probably be better than checking for a blank title.

> if the window gets closed it would be moot if it did anyways because there should be no WindowInfo class attached to a closed event because the window no longer exists and none of the methods in it can function properly.

The methods aren't the only reason for having a payload. When I first created this fork of Task Monitor, it was so I could see the window's title, for uses like I describe above. That information is still useful for learning more about the window that just closed.

The methods came as an afterthought, one which you picked up and greatly expanded on. They will all give some sort of error if called for a closed window. That said, it might be better if we made our own assert function that raises a well-defined exception, rather than just letting the low-level functions barf in their unique ways.

**Comment by kdschlosser** [comment]
I am a dingdong with the .format thing. I am used to seeing explicit keys or indicies when {} is used. 

So if you have 2 paramteres you are passing to format you would use {0} and {1} for the indicies of *args. Sorry that is my bad. I'm an idiot on that one. I am trying to think of the best way to deal with the title of the window. You could use types.ClassType to a dynamic class using the WindowInfo class as a template and name the class the same as the window it's self. This way if you use self.__class__.__name__ it will display the original window title. I ha e not tried the new release of the plugin yet so I do not know exactly what you have updated. But as far as the docstrings go we are going to be making a push to use sphinx to create help docs for the plugins based on what is in the docstrings this way it might be easier for a developer to do them instead of having to key out some markdown or rst or html in a parameter passed to eg register plugin. This is still an ongoing conversation but I think it is something we are leaning twords. So read up on the sphinx docstrings and formatting. As we do currently use this to generate the docs on the internal bits of EG. Again this is suggestion. It's your plugin. I just hate to see someone have to do more work later down the road. It's not my rule or anything but it's kind of a Python standard thing.

**Pull request closed without merging**
